name: Build page and output to master

on:
  push:
    branches:
      - 'page/**'

jobs:
  compile:
    name: 'Compile Page'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Branch'
        uses: 'actions/checkout@v3'
        with:
          featch-depth: 0

      - name: 'Get directory name for branch'
        id: 'getdir'
        run: |
          id=$(echo $GITHUB_REF_NAME | cut -d/ -f2)
          echo "::set-output name=dirname::$id"

      - name: 'Check if there is a build script'
        id: 'has_build_script'
        uses: 'andstor/file-existence-action@v1'
        with:
          files: 'build.sh'

      - name: Create output directory
        run: mkdir ./${{ steps.getdir.outputs.dirname }}

      - name: 'Build script does not exist: Copying files from /src to /master/${{ steps.getdir.outputs.dirname }}'
        if: steps.has_build_script.outputs.files_exists != 'true'
        run: cp -v -r ./src/. ./${{ steps.getdir.outputs.dirname }}

      - name: 'Build script exists: Running build script and then copying files from /build to /master/${{ steps.getdir.outputs.dirname }}'
        if: steps.has_build_script.outputs.files_exists == 'true'
        run: |
          chmod u+x ./build.sh
          ./build.sh
          cp -v -r ./build/. ./${{ steps.getdir.outputs.dirname }}

      - name: 'Commit built page to master branch'
        run: |
          git config --global user.name "SReject"
          git config --global user.email 'SReject@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git stash push -u -- ./${{ steps.getdir.outputs.dirname}}/*
          git restore .
          git fetch
          git checkout master
          rm -vrf ./${{ steps.getdir.outputs.dirname }}
          git stash pop
          git add .
          git commit -m "Changes from #$(echo ${GITHUB_SHA} | cut -c1-8)"
          git push origin master