name: Compile page for GH Pages

on:
  workflow_dispatch:
  push:
    branches:
      - 'page/**'
    branches_ignore:
      - 'page/**/*'

jobs:
  compile:
    name: 'Compile Page'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Branch'
        uses: 'actions/checkout@v3'

      - name: 'Get directory name of page'
        id: 'getpagedir'
        run: |
          id=$(echo ${{GETHUB_REF##*/}} | cut -d/ -f2)
          echo "::set-output name=dirname::$id"

      - name: 'Create directory for master branch'
        run: mkdir $GITHUB_WORKSPACE/master

      - name: 'Checkout master branch'
        uses: 'actions/checkout@v3'
        with:
          ref: 'master'
          path: 'master'

      - name: 'Create page directory in master branch'
        run: mkdir $GITHUB_WORKSPACE/master/${{ steps.getpagedir.outputs.dirname }}

      - name: 'Check if there is a build script'
        id: 'has_build_script'
        uses: 'actions/file-existence-action@v1'
        with:
          files: '$GITHUB_WORKSPACE/build.bat'

      - name: 'Build script does not exist: Copy files from /src to page directory'
        if: steps.has_build_script.outputs.files_exists != 'true'
        run: cp -r $GITHUB_WORKSPACE/src $GITHUB_WORKSPACE/master/${{ steps.getpagedir.outputs.dirname }}

      - name: 'Build script exists: run build script and then copy files from /build to page directory'
        if: steps.has_build_script.outputs.files_exists == 'true'
        run: |
          mkdir $GITHUB_WORKSPACE/build
          $GITHUB_WORKSPACE/build.bat
          cp -r $GETHUB_WORKSPACE/build $GETHUB_WORKSPACE/master/${{ steps.getpagedir.outputs.dirname }}

      - name: 'Commit built page to master branch'
        run: |
          cd master
          git add --all
          git commit -m 'Changes from #$GITHUB_SHA'
          git push origin master